-- Snowflake UDF to map category labels to primary categories
-- Created: 2025-10-31
-- Source: final_categories_20251031.csv

CREATE OR REPLACE FUNCTION MAP_CATEGORY_LABEL_TO_PRIMARY(CATEGORY_LABEL VARCHAR)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
AS
$$
  // Mapping dictionary from category_label to category_primary
  var categoryMapping = {
  "campground": "Accommodation & Lodging",
  "beach_resort": "Accommodation & Lodging",
  "apartment_agent": "Accommodation & Lodging",
  "apartments": "Accommodation & Lodging",
  "hotel_supply_service": "Business-to-Business",
  "bed_and_breakfast": "Accommodation & Lodging",
  "resort": "Accommodation & Lodging",
  "vacation_rental_agents": "Accommodation & Lodging",
  "motel": "Accommodation & Lodging",
  "cottage": "Accommodation & Lodging",
  "low_income_housing": "Accommodation & Lodging",
  "cabinet_sales_service": "Construction & Contractors",
  "houseboat": "Accommodation & Lodging",
  "inn": "Accommodation & Lodging",
  "self_catering_accommodation": "Accommodation & Lodging",
  "guest_house": "Accommodation & Lodging",
  "pension": "Financial Services",
  "rv_park": "Accommodation & Lodging",
  "cabin": "Accommodation & Lodging",
  "hostel": "Accommodation & Lodging",
  "hotel": "Accommodation & Lodging",
  "service_apartments": "Accommodation & Lodging",
  "condominium": "Accommodation & Lodging",
  "lodge": "Accommodation & Lodging",
  "housing_authorities": "Accommodation & Lodging",
  "accommodation": "Accommodation & Lodging",
  "fish_farm": "Agriculture & Farming",
  "pumpkin_patch": "Agriculture & Farming",
  "csa_farm": "Agriculture & Farming",
  "pig_farm": "Agriculture & Farming",
  "urban_farm": "Agriculture & Farming",
  "farming_services": "Agriculture & Farming",
  "fish_farms_and_hatcheries": "Agriculture & Farming",
  "orchard": "Agriculture & Farming",
  "ranch": "Agriculture & Farming",
  "agriculture": "Agriculture & Farming",
  "grain_elevators": "Agriculture & Farming",
  "b2b_farms": "Business-to-Business",
  "poultry_farm": "Agriculture & Farming",
  "dairy_farm": "Agriculture & Farming",
  "agricultural_service": "Agriculture & Farming",
  "agriculture_association": "Agriculture & Farming",
  "poultry_farming": "Agriculture & Farming",
  "b2b_farming": "Business-to-Business",
  "farm": "Agriculture & Farming",
  "beer_wine_and_spirits": "Agriculture & Farming",
  "apiaries_and_beekeepers": "Agriculture & Farming",
  "produce_wholesaler": "Agriculture & Farming",
  "pick_your_own_farm": "Agriculture & Farming",
  "haunted_house": "Arts & Entertainment",
  "clown": "Arts & Entertainment",
  "agricultural_cooperatives": "Arts & Entertainment",
  "zoo": "Arts & Entertainment",
  "studio_taping": "Arts & Entertainment",
  "virtual_reality_center": "Arts & Entertainment",
  "history_museum": "Arts & Entertainment",
  "performing_arts": "Arts & Entertainment",
  "circus": "Arts & Entertainment",
  "sports_museum": "Arts & Entertainment",
  "aquarium": "Arts & Entertainment",
  "agricultural_production": "Arts & Entertainment",
  "music_festivals_and_organizations": "Arts & Entertainment",
  "art_school": "Arts & Entertainment",
  "topic_concert_venue": "Arts & Entertainment",
  "trade_fair": "Arts & Entertainment",
  "musical_band_orchestras_and_symphonies": "Arts & Entertainment",
  "dance_club": "Arts & Entertainment",
  "opera_and_ballet": "Arts & Entertainment",
  "general_festivals": "Arts & Entertainment",
  "audio_visual_production_and_design": "Arts & Entertainment",
  "escape_rooms": "Arts & Entertainment",
  "henna_artist": "Arts & Entertainment",
  "crops_production": "Arts & Entertainment",
  "water_park": "Arts & Entertainment",
  "cultural_center": "Arts & Entertainment",
  "choir": "Arts & Entertainment",
  "contemporary_art_museum": "Arts & Entertainment",
  "adult_entertainment": "Arts & Entertainment",
  "art_gallery": "Arts & Entertainment",
  "observatory": "Arts & Entertainment",
  "festival": "Arts & Entertainment",
  "entertainment_law": "Arts & Entertainment",
  "film_festivals_and_organizations": "Arts & Entertainment",
  "computer_museum": "Arts & Entertainment",
  "planetarium": "Arts & Entertainment",
  "amusement_park": "Arts & Entertainment",
  "orchards_production": "Arts & Entertainment",
  "arts_and_entertainment": "Arts & Entertainment",
  "community_museum": "Arts & Entertainment",
  "commissioned_artist": "Arts & Entertainment",
  "video_film_production": "Arts & Entertainment",
  "recording_and_rehearsal_studio": "Arts & Entertainment",
  "rodeo": "Arts & Entertainment",
  "design_museum": "Arts & Entertainment",
  "theatre": "Arts & Entertainment",
  "karaoke": "Arts & Entertainment",
  "asian_art_museum": "Arts & Entertainment",
  "corporate_entertainment_services": "Arts & Entertainment",
  "qi_gong_studio": "Beauty & Wellness",
  "comedy_club": "Arts & Entertainment",
  "state_museum": "Arts & Entertainment",
  "drive_in_theater": "Arts & Entertainment",
  "tai_chi_studio": "Beauty & Wellness",
  "music_production_services": "Arts & Entertainment",
  "photography_museum": "Arts & Entertainment",
  "broadcasting_media_production": "Arts & Entertainment",
  "national_museum": "Arts & Entertainment",
  "theatrical_productions": "Arts & Entertainment",
  "aviation_museum": "Arts & Entertainment",
  "outdoor_movies": "Arts & Entertainment",
  "aquarium_services": "Arts & Entertainment",
  "decorative_arts_museum": "Arts & Entertainment",
  "music_production": "Arts & Entertainment",
  "magician": "Arts & Entertainment",
  "theaters_and_performance_venues": "Arts & Entertainment",
  "art_tours": "Arts & Entertainment",
  "petting_zoo": "Arts & Entertainment",
  "cinema": "Arts & Entertainment",
  "movie_television_studio": "Arts & Entertainment",
  "housing_cooperative": "Arts & Entertainment",
  "costume_museum": "Arts & Entertainment",
  "dance_school": "Arts & Entertainment",
  "science_museum": "Arts & Entertainment",
  "animation_studio": "Arts & Entertainment",
  "childrens_museum": "Arts & Entertainment",
  "music_venue": "Arts & Entertainment",
  "art_museum": "Arts & Entertainment",
  "arcade": "Arts & Entertainment",
  "circus_school": "Arts & Entertainment",
  "karaoke_rental": "Arts & Entertainment",
  "military_museum": "Arts & Entertainment",
  "botanical_garden": "Arts & Entertainment",
  "fair": "Arts & Entertainment",
  "drama_school": "Arts & Entertainment",
  "bingo_hall": "Arts & Entertainment",
  "modern_art_museum": "Arts & Entertainment",
  "casino": "Arts & Entertainment",
  "grain_production": "Arts & Entertainment",
  "museum": "Arts & Entertainment",
  "civilization_museum": "Arts & Entertainment",
  "dinner_theater": "Arts & Entertainment",
  "commercial_vehicle_dealer": "Automotive",
  "emissions_inspection": "Automotive",
  "b2b_forklift_dealers": "Business-to-Business",
  "foundation_repair": "Automotive",
  "coin_dealers": "Automotive",
  "shoe_repair": "Automotive",
  "hydraulic_repair_service": "Automotive",
  "trailer_dealer": "Automotive",
  "b2b_equipment_maintenance_and_repair": "Business-to-Business",
  "automotive_parts_and_accessories": "Automotive",
  "wheel_and_rim_repair": "Automotive",
  "auto_customization": "Automotive",
  "auto_glass_service": "Automotive",
  "forklift_dealer": "Automotive",
  "car_inspection": "Automotive",
  "media_restoration_service": "Automotive",
  "car_buyer": "Automotive",
  "b2b_truck_equipment_parts_and_accessories": "Business-to-Business",
  "boat_service_and_repair": "Automotive",
  "motorcycle_rentals": "Automotive",
  "car_dealer": "Automotive",
  "truck_rentals": "Automotive",
  "motorcycle_dealer": "Automotive",
  "recreation_vehicle_repair": "Automotive",
  "mobile_home_dealer": "Automotive",
  "car_wash": "Automotive",
  "brake_service_and_repair": "Automotive",
  "automation_services": "Automotive",
  "automotive_wheel_polishing_service": "Automotive",
  "exhaust_and_muffler_repair": "Automotive",
  "car_broker": "Automotive",
  "car_window_tinting": "Automotive",
  "department_of_motor_vehicles": "Automotive",
  "tire_dealer_and_repair": "Automotive",
  "towing_service": "Automotive",
  "jewelry_repair_service": "Automotive",
  "car_rental_agency": "Automotive",
  "inspection_services": "Automotive",
  "truck_dealer": "Automotive",
  "bike_repair_maintenance": "Automotive",
  "mobile_home_repair": "Automotive",
  "trucks_and_industrial_vehicles": "Automotive",
  "automotive_services_and_repair": "Automotive",
  "truck_repair": "Automotive",
  "clock_repair_service": "Automotive",
  "b2b_autos_and_vehicles": "Business-to-Business",
  "fire_and_water_damage_restoration": "Automotive",
  "auto_security": "Automotive",
  "motorcycle_gear": "Automotive",
  "car_stereo_installation": "Automotive",
  "farm_equipment_repair_service": "Automotive",
  "auto_detailing": "Automotive",
  "car_auction": "Automotive",
  "boat_dealer": "Automotive",
  "it_service_and_computer_repair": "Automotive",
  "truck_dealer_for_businesses": "Automotive",
  "automotive_repair": "Automotive",
  "home_automation": "Automotive",
  "hybrid_car_repair": "Automotive",
  "furniture_repair": "Automotive",
  "diamond_dealer": "Automotive",
  "automotive": "Automotive",
  "auto_loan_provider": "Automotive",
  "aircraft_repair": "Automotive",
  "used_car_dealer": "Automotive",
  "retirement_home": "Automotive",
  "automotive_dealer": "Automotive",
  "water_heater_installation_repair": "Automotive",
  "motorsport_vehicle_repair": "Automotive",
  "art_restoration_service": "Automotive",
  "vehicle_wrap": "Automotive",
  "mobile_phone_repair": "Automotive",
  "recreational_vehicle_parts_and_accessories": "Automotive",
  "b2b_tires": "Business-to-Business",
  "washer_and_dryer_repair_service": "Automotive",
  "recreational_vehicle_dealer": "Automotive",
  "vehicle_shipping": "Automotive",
  "watch_repair_service": "Automotive",
  "automotive_consultant": "Automotive",
  "windshield_installation_and_repair": "Automotive",
  "gas_station": "Automotive",
  "auto_insurance": "Automotive",
  "art_restoration": "Automotive",
  "auto_electrical_repair": "Automotive",
  "scooter_dealers": "Automotive",
  "home_window_tinting": "Automotive",
  "bathtub_and_sink_repairs": "Automotive",
  "cable_car_service": "Automotive",
  "truck_gas_station": "Automotive",
  "damage_restoration": "Automotive",
  "auto_manufacturers_and_distributors": "Automotive",
  "motorcycle_repair": "Automotive",
  "car_sharing": "Automotive",
  "aircraft_dealer": "Automotive",
  "generator_installation_repair": "Automotive",
  "lawn_mower_repair_service": "Automotive",
  "automobile_leasing": "Automotive",
  "b2b_tractor_dealers": "Automotive",
  "motorsport_vehicle_dealer": "Automotive",
  "mobile_dent_repair": "Automotive",
  "livestock_dealers": "Automotive",
  "auto_company": "Automotive",
  "automobile_registration_service": "Automotive",
  "transmission_repair": "Automotive",
  "fuel_dock": "Automotive",
  "ceiling_and_roofing_repair_and_service": "Construction & Contractors",
  "town_car_service": "Automotive",
  "mechanical_engineers": "Automotive",
  "engine_repair_service": "Automotive",
  "automotive_storage_facility": "Automotive",
  "auto_restoration_services": "Automotive",
  "appliance_repair_service": "Automotive",
  "furniture_reupholstery": "Automotive",
  "auto_upholstery": "Automotive",
  "trailer_repair": "Automotive",
  "oil_change_station": "Automotive",
  "motorcycle_manufacturer": "Automotive",
  "game_truck_rental": "Automotive",
  "golf_cart_dealer": "Automotive",
  "eyelash_service": "Beauty & Wellness",
  "muay_thai_club": "Beauty & Wellness",
  "boot_camp": "Beauty & Wellness",
  "martial_arts_club": "Beauty & Wellness",
  "boxing_class": "Beauty & Wellness",
  "laser_hair_removal": "Beauty & Wellness",
  "nutritionist": "Beauty & Wellness",
  "coworking_space": "Beauty & Wellness",
  "makerspace": "Beauty & Wellness",
  "beauty_salon": "Beauty & Wellness",
  "tattoo_removal": "Beauty & Wellness",
  "kickboxing_club": "Beauty & Wellness",
  "aerial_fitness_center": "Beauty & Wellness",
  "reiki": "Beauty & Wellness",
  "shared_office_space": "Beauty & Wellness",
  "hair_extensions": "Beauty & Wellness",
  "boudoir_photography": "Beauty & Wellness",
  "yoga_instructor": "Beauty & Wellness",
  "fitness_trainer": "Beauty & Wellness",
  "beauty_and_spa": "Beauty & Wellness",
  "karate_club": "Beauty & Wellness",
  "tanning_bed": "Beauty & Wellness",
  "fitness_exercise_equipment": "Beauty & Wellness",
  "hair_salon": "Beauty & Wellness",
  "gymnastics_club": "Beauty & Wellness",
  "float_spa": "Beauty & Wellness",
  "eyebrow_service": "Beauty & Wellness",
  "hair_removal": "Beauty & Wellness",
  "skin_care": "Beauty & Wellness",
  "hair_loss_center": "Beauty & Wellness",
  "esthetician": "Beauty & Wellness",
  "gym": "Beauty & Wellness",
  "dietitian": "Beauty & Wellness",
  "day_spa": "Beauty & Wellness",
  "blow_dry_blow_out_service": "Beauty & Wellness",
  "tattoo_and_piercing": "Beauty & Wellness",
  "piercing": "Beauty & Wellness",
  "pilates_studio": "Beauty & Wellness",
  "venue_and_event_space": "Beauty & Wellness",
  "massage": "Beauty & Wellness",
  "gymnastics_center": "Beauty & Wellness",
  "horse_trainer": "Beauty & Wellness",
  "weight_loss_center": "Beauty & Wellness",
  "nail_salon": "Beauty & Wellness",
  "tattoo": "Beauty & Wellness",
  "sauna": "Beauty & Wellness",
  "chinese_martial_arts_club": "Beauty & Wellness",
  "art_space_rental": "Beauty & Wellness",
  "sports_and_fitness_instruction": "Beauty & Wellness",
  "fitness_equipment_wholesaler": "Beauty & Wellness",
  "yoga_studio": "Beauty & Wellness",
  "brazilian_jiu_jitsu_club": "Beauty & Wellness",
  "dog_trainer": "Beauty & Wellness",
  "tanning_salon": "Beauty & Wellness",
  "waxing": "Beauty & Wellness",
  "threading_service": "Beauty & Wellness",
  "sugaring": "Beauty & Wellness",
  "spray_tanning": "Beauty & Wellness",
  "hair_stylist": "Beauty & Wellness",
  "spas": "Beauty & Wellness",
  "boxing_club": "Beauty & Wellness",
  "kids_hair_salon": "Beauty & Wellness",
  "rock_climbing_gym": "Beauty & Wellness",
  "taekwondo_club": "Beauty & Wellness",
  "newspaper_advertising": "Beauty & Wellness",
  "cosmetic_and_beauty_supplies": "Beauty & Wellness",
  "hair_replacement": "Beauty & Wellness",
  "boxing_gym": "Beauty & Wellness",
  "makeup_artist": "Beauty & Wellness",
  "aesthetician": "Beauty & Wellness",
  "permanent_makeup": "Beauty & Wellness",
  "electronic_parts_supplier": "Business-to-Business",
  "b2b_scientific_equipment": "Business-to-Business",
  "propane_supplier": "Business-to-Business",
  "corporate_gift_supplier": "Business-to-Business",
  "fastener_supplier": "Business-to-Business",
  "b2b_furniture_and_housewares": "Business-to-Business",
  "bearing_supplier": "Business-to-Business",
  "vending_machine_supplier": "Business-to-Business",
  "granite_supplier": "Business-to-Business",
  "cement_supplier": "Business-to-Business",
  "ice_supplier": "Business-to-Business",
  "b2b_hardware": "Business-to-Business",
  "scale_supplier": "Business-to-Business",
  "pipe_supplier": "Business-to-Business",
  "aluminum_supplier": "Business-to-Business",
  "stone_supplier": "Business-to-Business",
  "awning_supplier": "Business-to-Business",
  "beverage_supplier": "Business-to-Business",
  "beauty_product_supplier": "Business-to-Business",
  "b2b_science_and_technology": "Business-to-Business",
  "abrasives_supplier": "Business-to-Business",
  "natural_gas_supplier": "Business-to-Business",
  "b2b_dairies": "Business-to-Business",
  "tableware_supplier": "Business-to-Business",
  "box_lunch_supplier": "Business-to-Business",
  "water_softening_equipment_supplier": "Business-to-Business",
  "b2b_jewelers": "Business-to-Business",
  "sand_and_gravel_supplier": "Business-to-Business",
  "b2b_machinery_and_tools": "Business-to-Business",
  "thread_supplier": "Business-to-Business",
  "retaining_wall_supplier": "Business-to-Business",
  "hydraulic_equipment_supplier": "Business-to-Business",
  "b2b_electronic_equipment": "Business-to-Business",
  "laboratory_equipment_supplier": "Business-to-Business",
  "window_supplier": "Business-to-Business",
  "aggregate_supplier": "Business-to-Business",
  "suicide_prevention_services": "Community & Social Services",
  "elder_care_planning": "Community & Social Services",
  "community_center": "Community & Social Services",
  "home_organization": "Community & Social Services",
  "donation_center": "Community & Social Services",
  "charity_organization": "Community & Social Services",
  "foster_care_services": "Community & Social Services",
  "organization": "Community & Social Services",
  "crisis_intervention_services": "Community & Social Services",
  "fraternal_organization": "Community & Social Services",
  "volunteer_association": "Community & Social Services",
  "homeowner_association": "Community & Social Services",
  "career_counseling": "Community & Social Services",
  "senior_citizen_services": "Community & Social Services",
  "welders": "Community & Social Services",
  "domestic_business_and_trade_organizations": "Community & Social Services",
  "blood_and_plasma_donation_center": "Community & Social Services",
  "labor_union": "Community & Social Services",
  "political_organization": "Community & Social Services",
  "youth_organizations": "Community & Social Services",
  "social_service_organizations": "Community & Social Services",
  "community_services_non_profits": "Community & Social Services",
  "private_association": "Community & Social Services",
  "gay_and_lesbian_services_organization": "Community & Social Services",
  "veterans_organization": "Community & Social Services",
  "packaging_contractors_and_service": "Construction & Contractors",
  "contractor": "Construction & Contractors",
  "kitchen_remodeling": "Construction & Contractors",
  "painting": "Construction & Contractors",
  "plumbing": "Construction & Contractors",
  "roofing": "Construction & Contractors",
  "closet_remodeling": "Construction & Contractors",
  "construction_services": "Construction & Contractors",
  "demolition_service": "Construction & Contractors",
  "carpenter": "Construction & Contractors",
  "excavation_service": "Construction & Contractors",
  "tiling": "Construction & Contractors",
  "road_contractor": "Construction & Contractors",
  "logging_contractor": "Construction & Contractors",
  "well_drilling": "Construction & Contractors",
  "stone_and_masonry": "Construction & Contractors",
  "boat_builder": "Construction & Contractors",
  "paving_contractor": "Construction & Contractors",
  "masonry_contractors": "Construction & Contractors",
  "face_painting": "Construction & Contractors",
  "waterproofing": "Construction & Contractors",
  "siding": "Construction & Contractors",
  "electrician": "Construction & Contractors",
  "insulation_installation": "Construction & Contractors",
  "flooring_contractors": "Construction & Contractors",
  "hvac_supplier": "Construction & Contractors",
  "altering_and_remodeling_contractor": "Construction & Contractors",
  "building_contractor": "Construction & Contractors",
  "masonry_concrete": "Construction & Contractors",
  "septic_services": "Construction & Contractors",
  "hvac_services": "Construction & Contractors",
  "bathroom_remodeling": "Construction & Contractors",
  "childproofing": "Construction & Contractors",
  "builders": "Construction & Contractors",
  "drywall_services": "Construction & Contractors",
  "vocal_coach": "Education",
  "science_schools": "Education",
  "cardio_classes": "Exercise/Wellness",
  "law_schools": "Education",
  "child_care_and_day_care": "Education",
  "cpr_classes": "Education",
  "wine_tasting_classes": "Education",
  "tutoring_center": "Education",
  "boat_rental_and_training": "Education",
  "architecture_schools": "Education",
  "parenting_classes": "Education",
  "middle_school": "Education",
  "school": "Education",
  "adult_education": "Education",
  "flight_school": "Education",
  "speech_training": "Education",
  "educational_camp": "Education",
  "educational_research_institute": "Education",
  "self_defense_classes": "Exercise/Wellness",
  "day_care_preschool": "Education",
  "private_school": "Education",
  "life_coach": "Education",
  "montessori_school": "Education",
  "first_aid_class": "Education",
  "vocational_and_technical_school": "Education",
  "educational_services": "Education",
  "cooking_classes": "Education",
  "business_schools": "Education",
  "engineering_schools": "Education",
  "preschool": "Education",
  "library": "Education",
  "dui_school": "Education",
  "religious_school": "Education",
  "charter_school": "Education",
  "after_school_program": "Education",
  "research_institute": "Education",
  "elementary_school": "Education",
  "education": "Education",
  "waldorf_school": "Education",
  "pet_training": "Education",
  "high_school": "Education",
  "school_district_offices": "Education",
  "massage_school": "Education",
  "tasting_classes": "Education",
  "cycling_classes": "Beauty & Wellness",
  "student_union": "Education",
  "childbirth_education": "Education",
  "language_school": "Education",
  "university_housing": "Education",
  "music_school": "Education",
  "computer_coaching": "Education",
  "college_counseling": "Education",
  "specialty_school": "Education",
  "cosmetology_school": "Education",
  "cooking_school": "Education",
  "coach_bus": "Transportation",
  "board_of_education_offices": "Education",
  "college_university": "Education",
  "swimming_instructor": "Education",
  "firearm_training": "Education",
  "photography_classes": "Education",
  "furniture_rental_service": "Event Services",
  "rental_service": "Event Services",
  "florist": "Event Services",
  "political_party_office": "Event Services",
  "party_equipment_rental": "Event Services",
  "party_character": "Event Services",
  "wedding_planning": "Event Services",
  "party_bus_rental": "Event Services",
  "photo_booth_rental": "Event Services",
  "event_planning": "Event Services",
  "dj_service": "Event Services",
  "party_and_event_planning": "Event Services",
  "rental_services": "Event Services",
  "party_bike_rental": "Event Services",
  "wholesale_florist": "Event Services",
  "balloon_services": "Event Services",
  "credit_union": "Financial Services",
  "installment_loans": "Financial Services",
  "business_banking_service": "Financial Services",
  "bank_credit_union": "Financial Services",
  "currency_exchange": "Financial Services",
  "livestock_breeder": "Financial Services",
  "customs_broker": "Financial Services",
  "debt_relief_services": "Financial Services",
  "farm_insurance": "Financial Services",
  "atms": "Financial Services",
  "real_estate_investment": "Financial Services",
  "insurance_agency": "Financial Services",
  "stock_and_bond_brokers": "Financial Services",
  "abuse_and_addiction_treatment": "Financial Services",
  "banks": "Financial Services",
  "water_treatment_equipment_and_services": "Financial Services",
  "alcohol_and_drug_treatment_centers": "Financial Services",
  "alcohol_and_drug_treatment_center": "Financial Services",
  "bank_equipment_service": "Financial Services",
  "business_brokers": "Financial Services",
  "life_insurance": "Financial Services",
  "lice_treatment": "Financial Services",
  "tax_office": "Financial Services",
  "brokers": "Financial Services",
  "pet_insurance": "Financial Services",
  "cancer_treatment_center": "Financial Services",
  "mortgage_broker": "Financial Services",
  "mortgage_lender": "Financial Services",
  "home_and_rental_insurance": "Financial Services",
  "check_cashing_payday_loans": "Financial Services",
  "bail_bonds_service": "Financial Services",
  "thai_restaurant": "Food & Dining",
  "hookah_bar": "Food & Dining",
  "ice_cream_and_frozen_yoghurt": "Food & Dining",
  "champagne_bar": "Food & Dining",
  "undersea_hyperbaric_medicine": "Healthcare & Medical",
  "halal_restaurant": "Food & Dining",
  "irish_restaurant": "Food & Dining",
  "brasserie": "Food & Dining",
  "public_phones": "Other Services",
  "venezuelan_restaurant": "Food & Dining",
  "eastern_european_restaurant": "Food & Dining",
  "specialty_foods": "Food & Dining",
  "speakeasy": "Food & Dining",
  "scandinavian_restaurant": "Food & Dining",
  "danish_restaurant": "Food & Dining",
  "b2b_food_products": "Business-to-Business",
  "seafood_restaurant": "Food & Dining",
  "fish_restaurant": "Food & Dining",
  "afghan_restaurant": "Food & Dining",
  "barbecue_restaurant": "Food & Dining",
  "pasta_shop": "Food & Dining",
  "honduran_restaurant": "Food & Dining",
  "malaysian_restaurant": "Food & Dining",
  "coffee_and_tea_supplies": "Business-to-Business",
  "european_restaurant": "Food & Dining",
  "vermouth_bar": "Food & Dining",
  "coffee_shop": "Food & Dining",
  "bartender": "Food & Dining",
  "sandwich_shop": "Food & Dining",
  "frozen_foods": "Food & Dining",
  "argentine_restaurant": "Food & Dining",
  "poke_restaurant": "Food & Dining",
  "barre_classes": "Beauty & Wellness",
  "cajun_and_creole_restaurant": "Food & Dining",
  "food_stand": "Food & Dining",
  "texmex_restaurant": "Food & Dining",
  "diner": "Food & Dining",
  "diy_foods_restaurant": "Food & Dining",
  "food_consultant": "Food & Dining",
  "food_and_beverage_exporter": "Food & Dining",
  "gastropub": "Food & Dining",
  "barber": "Food & Dining",
  "cidery": "Food & Dining",
  "puerto_rican_restaurant": "Food & Dining",
  "armenian_restaurant": "Food & Dining",
  "sake_bar": "Food & Dining",
  "topic_publisher": "Food & Dining",
  "food_beverage_service_distribution": "Food & Dining",
  "breakfast_and_brunch_restaurant": "Food & Dining",
  "beer_bar": "Food & Dining",
  "indo_chinese_restaurant": "Food & Dining",
  "egyptian_restaurant": "Food & Dining",
  "belgian_restaurant": "Food & Dining",
  "irish_pub": "Food & Dining",
  "gluten_free_restaurant": "Food & Dining",
  "vietnamese_restaurant": "Food & Dining",
  "cheese_shop": "Food & Dining",
  "cigar_bar": "Food & Dining",
  "cuban_restaurant": "Food & Dining",
  "game_publisher": "Food & Dining",
  "sri_lankan_restaurant": "Food & Dining",
  "beach_bar": "Food & Dining",
  "chicken_restaurant": "Food & Dining",
  "sports_bar": "Food & Dining",
  "south_african_restaurant": "Food & Dining",
  "nicaraguan_restaurant": "Food & Dining",
  "public_bath_houses": "Food & Dining",
  "african_restaurant": "Food & Dining",
  "bistro": "Food & Dining",
  "hawaiian_restaurant": "Food & Dining",
  "fish_and_chips_restaurant": "Food & Dining",
  "restaurant": "Food & Dining",
  "israeli_restaurant": "Food & Dining",
  "dim_sum_restaurant": "Food & Dining",
  "shaved_ice_shop": "Food & Dining",
  "polynesian_restaurant": "Food & Dining",
  "restaurant_equipment_and_supply": "Food & Dining",
  "public_utility_company": "Food & Dining",
  "syrian_restaurant": "Food & Dining",
  "czech_restaurant": "Food & Dining",
  "eat_and_drink": "Food & Dining",
  "drive_thru_bar": "Food & Dining",
  "distillery": "Food & Dining",
  "cafe": "Food & Dining",
  "public_health_clinic": "Food & Dining",
  "basque_restaurant": "Food & Dining",
  "southern_restaurant": "Food & Dining",
  "pop_up_restaurant": "Food & Dining",
  "public_and_government_association": "Food & Dining",
  "publicity_service": "Food & Dining",
  "soul_food": "Food & Dining",
  "restaurant_wholesale": "Food & Dining",
  "food_tours": "Food & Dining",
  "uruguayan_restaurant": "Food & Dining",
  "public_restrooms": "Food & Dining",
  "live_and_raw_food_restaurant": "Food & Dining",
  "scottish_restaurant": "Food & Dining",
  "airport_lounge": "Food & Dining",
  "filipino_restaurant": "Food & Dining",
  "taco_restaurant": "Food & Dining",
  "molecular_gastronomy_restaurant": "Food & Dining",
  "lebanese_restaurant": "Food & Dining",
  "canadian_restaurant": "Food & Dining",
  "salvadoran_restaurant": "Food & Dining",
  "vegan_restaurant": "Food & Dining",
  "kosher_restaurant": "Food & Dining",
  "trinidadian_restaurant": "Food & Dining",
  "pretzels": "Food & Dining",
  "hot_dog_restaurant": "Food & Dining",
  "jamaican_restaurant": "Food & Dining",
  "donuts": "Food & Dining",
  "pie_shop": "Food & Dining",
  "frozen_yoghurt_shop": "Food & Dining",
  "mexican_restaurant": "Food & Dining",
  "poutinerie_restaurant": "Food & Dining",
  "asian_restaurant": "Food & Dining",
  "health_food_restaurant": "Food & Dining",
  "pakistani_restaurant": "Food & Dining",
  "wine_bar": "Food & Dining",
  "theme_restaurant": "Food & Dining",
  "polish_restaurant": "Food & Dining",
  "meat_restaurant": "Food & Dining",
  "bartending_school": "Food & Dining",
  "colombian_restaurant": "Food & Dining",
  "brazilian_restaurant": "Food & Dining",
  "chilean_restaurant": "Food & Dining",
  "hungarian_restaurant": "Food & Dining",
  "comfort_food_restaurant": "Food & Dining",
  "austrian_restaurant": "Food & Dining",
  "gay_bar": "Food & Dining",
  "kurdish_restaurant": "Food & Dining",
  "serbo_croatian_restaurant": "Food & Dining",
  "food_truck": "Food & Dining",
  "tapas_bar": "Food & Dining",
  "pan_asian_restaurant": "Food & Dining",
  "wrap_restaurant": "Food & Dining",
  "bangladeshi_restaurant": "Food & Dining",
  "lounge": "Food & Dining",
  "cambodian_restaurant": "Food & Dining",
  "swiss_restaurant": "Food & Dining",
  "pizza_delivery_service": "Food & Dining",
  "cocktail_bar": "Food & Dining",
  "haitian_restaurant": "Food & Dining",
  "turkish_restaurant": "Food & Dining",
  "soup_restaurant": "Food & Dining",
  "spanish_restaurant": "Food & Dining",
  "arabian_restaurant": "Food & Dining",
  "empanadas": "Food & Dining",
  "public_relations": "Food & Dining",
  "dominican_restaurant": "Food & Dining",
  "popcorn_shop": "Food & Dining",
  "piano_bar": "Food & Dining",
  "whiskey_bar": "Food & Dining",
  "b2b_agriculture_and_food": "Food & Dining",
  "coffee_roastery": "Food & Dining",
  "food_banks": "Food & Dining",
  "fast_food_restaurant": "Food & Dining",
  "restaurant_management": "Food & Dining",
  "noodles_restaurant": "Food & Dining",
  "paraguayan_restaurant": "Food & Dining",
  "korean_restaurant": "Food & Dining",
  "iberian_restaurant": "Food & Dining",
  "food_delivery_service": "Food & Dining",
  "chinese_restaurant": "Food & Dining",
  "bakery": "Food & Dining",
  "taiwanese_restaurant": "Food & Dining",
  "butcher_shop": "Food & Dining",
  "latin_american_restaurant": "Food & Dining",
  "dive_bar": "Food & Dining",
  "panamanian_restaurant": "Food & Dining",
  "costa_rican_restaurant": "Food & Dining",
  "nigerian_restaurant": "Food & Dining",
  "vegetarian_restaurant": "Food & Dining",
  "seafood_wholesaler": "Food & Dining",
  "italian_restaurant": "Food & Dining",
  "patisserie_cake_shop": "Food & Dining",
  "uzbek_restaurant": "Food & Dining",
  "winery": "Food & Dining",
  "chicken_wings_restaurant": "Food & Dining",
  "ecuadorian_restaurant": "Food & Dining",
  "burmese_restaurant": "Food & Dining",
  "australian_restaurant": "Food & Dining",
  "international_restaurant": "Food & Dining",
  "falafel_restaurant": "Food & Dining",
  "caribbean_restaurant": "Food & Dining",
  "delicatessen": "Food & Dining",
  "brewery": "Food & Dining",
  "ethiopian_restaurant": "Food & Dining",
  "russian_restaurant": "Food & Dining",
  "georgian_restaurant": "Food & Dining",
  "flatbread_restaurant": "Food & Dining",
  "health_food_store": "Food & Dining",
  "food_and_beverage_consultant": "Food & Dining",
  "meat_shop": "Food & Dining",
  "buffet_restaurant": "Food & Dining",
  "indian_restaurant": "Food & Dining",
  "food": "Food & Dining",
  "doner_kebab": "Food & Dining",
  "waffle_restaurant": "Food & Dining",
  "tiki_bar": "Food & Dining",
  "japanese_restaurant": "Food & Dining",
  "laotian_restaurant": "Food & Dining",
  "mediterranean_restaurant": "Food & Dining",
  "seafood_market": "Food & Dining",
  "cabaret": "Food & Dining",
  "pub": "Food & Dining",
  "bar_crawl": "Food & Dining",
  "smoothie_juice_bar": "Food & Dining",
  "pizza_restaurant": "Food & Dining",
  "burger_restaurant": "Food & Dining",
  "indonesian_restaurant": "Food & Dining",
  "ice_cream_shop": "Food & Dining",
  "persian_iranian_restaurant": "Food & Dining",
  "fondue_restaurant": "Food & Dining",
  "candy_store": "Food & Dining",
  "german_restaurant": "Food & Dining",
  "bagel_restaurant": "Food & Dining",
  "gelato": "Food & Dining",
  "food_safety_training": "Food & Dining",
  "public_service_and_government": "Food & Dining",
  "public_transportation": "Food & Dining",
  "ukrainian_restaurant": "Food & Dining",
  "salad_bar": "Food & Dining",
  "dumpling_restaurant": "Food & Dining",
  "guatemalan_restaurant": "Food & Dining",
  "french_restaurant": "Food & Dining",
  "bagel_shop": "Food & Dining",
  "bar": "Food & Dining",
  "hotel_bar": "Food & Dining",
  "kombucha": "Food & Dining",
  "oxygen_bar": "Food & Dining",
  "moroccan_restaurant": "Food & Dining",
  "acai_bowls": "Food & Dining",
  "british_restaurant": "Food & Dining",
  "middle_eastern_restaurant": "Food & Dining",
  "caterer": "Food & Dining",
  "public_plaza": "Food & Dining",
  "potato_restaurant": "Food & Dining",
  "pancake_house": "Food & Dining",
  "romanian_restaurant": "Food & Dining",
  "cupcake_shop": "Food & Dining",
  "wok_restaurant": "Food & Dining",
  "bubble_tea": "Food & Dining",
  "food_court": "Food & Dining",
  "tea_room": "Food & Dining",
  "american_restaurant": "Food & Dining",
  "slovakian_restaurant": "Food & Dining",
  "public_school": "Food & Dining",
  "singaporean_restaurant": "Food & Dining",
  "steakhouse": "Food & Dining",
  "greek_restaurant": "Food & Dining",
  "himalayan_nepalese_restaurant": "Food & Dining",
  "public_adjuster": "Food & Dining",
  "portuguese_restaurant": "Food & Dining",
  "public_toilet": "Food & Dining",
  "mongolian_restaurant": "Food & Dining",
  "peruvian_restaurant": "Food & Dining",
  "azerbaijani_restaurant": "Food & Dining",
  "desserts": "Food & Dining",
  "bolivian_restaurant": "Food & Dining",
  "hong_kong_style_cafe": "Food & Dining",
  "public_market": "Food & Dining",
  "bar_and_grill_restaurant": "Food & Dining",
  "asian_fusion_restaurant": "Food & Dining",
  "internet_cafe": "Food & Dining",
  "cheesesteak_restaurant": "Food & Dining",
  "bulgarian_restaurant": "Food & Dining",
  "sushi_restaurant": "Food & Dining",
  "notary_public": "Government & Public Services",
  "senegalese_restaurant": "Food & Dining",
  "imported_food": "Food & Dining",
  "bus_ticket_agency": "Government & Public Services",
  "fire_department": "Government & Public Services",
  "emergency_service": "Government & Public Services",
  "civic_center": "Government & Public Services",
  "jail_and_prison": "Government & Public Services",
  "social_security_services": "Government & Public Services",
  "talent_agency": "Government & Public Services",
  "police_department": "Government & Public Services",
  "national_security_services": "Government & Public Services",
  "local_and_state_government_offices": "Government & Public Services",
  "non_governmental_association": "Government & Public Services",
  "freight_forwarding_agency": "Government & Public Services",
  "government_services": "Government & Public Services",
  "juvenile_detention_center": "Government & Public Services",
  "town_hall": "Government & Public Services",
  "armed_forces_branch": "Government & Public Services",
  "media_agency": "Government & Public Services",
  "certification_agency": "Government & Public Services",
  "passport_and_visa_services": "Government & Public Services",
  "central_government_office": "Government & Public Services",
  "estate_liquidation": "Government & Public Services",
  "federal_government_offices": "Government & Public Services",
  "state_park": "Government & Public Services",
  "airline_ticket_agency": "Government & Public Services",
  "sightseeing_tour_agency": "Government & Public Services",
  "social_media_agency": "Government & Public Services",
  "department_of_social_service": "Government & Public Services",
  "post_office": "Government & Public Services",
  "embassy": "Government & Public Services",
  "office_of_vital_records": "Government & Public Services",
  "social_welfare_center": "Government & Public Services",
  "general_dentistry": "Healthcare & Medical",
  "mohel": "Healthcare & Medical",
  "maternity_centers": "Healthcare & Medical",
  "dental_laboratories": "Healthcare & Medical",
  "sports_psychologist": "Healthcare & Medical",
  "emergency_medicine": "Healthcare & Medical",
  "cardiologist": "Healthcare & Medical",
  "animal_hospital": "Pet Services",
  "midwife": "Healthcare & Medical",
  "cosmetic_dentist": "Healthcare & Medical",
  "physical_therapy": "Healthcare & Medical",
  "pediatric_surgery": "Healthcare & Medical",
  "vascular_medicine": "Healthcare & Medical",
  "occupational_medicine": "Healthcare & Medical",
  "family_counselor": "Healthcare & Medical",
  "alternative_medicine": "Healthcare & Medical",
  "otologist": "Healthcare & Medical",
  "aromatherapy": "Healthcare & Medical",
  "rehabilitation_center": "Healthcare & Medical",
  "health_market": "Healthcare & Medical",
  "lactation_services": "Healthcare & Medical",
  "pediatric_orthopedic_surgery": "Healthcare & Medical",
  "health_and_medical": "Healthcare & Medical",
  "pediatric_pulmonology": "Healthcare & Medical",
  "anesthesiologist": "Healthcare & Medical",
  "urologist": "Healthcare & Medical",
  "pulmonologist": "Healthcare & Medical",
  "health_coach": "Healthcare & Medical",
  "medical_center": "Healthcare & Medical",
  "halotherapy": "Healthcare & Medical",
  "pediatric_dentist": "Healthcare & Medical",
  "womens_health_clinic": "Healthcare & Medical",
  "community_health_center": "Healthcare & Medical",
  "optometrist": "Healthcare & Medical",
  "pediatric_neurology": "Healthcare & Medical",
  "pediatric_radiology": "Healthcare & Medical",
  "spine_surgeon": "Healthcare & Medical",
  "proctologist": "Healthcare & Medical",
  "gastroenterologist": "Healthcare & Medical",
  "hepatologist": "Healthcare & Medical",
  "ayurveda": "Healthcare & Medical",
  "doula": "Healthcare & Medical",
  "radiologist": "Healthcare & Medical",
  "pediatric_gastroenterology": "Healthcare & Medical",
  "fertility": "Healthcare & Medical",
  "b2b_medical_support_services": "Healthcare & Medical",
  "oncologist": "Healthcare & Medical",
  "physician_assistant": "Healthcare & Medical",
  "geneticist": "Healthcare & Medical",
  "retina_specialist": "Healthcare & Medical",
  "medical_supply": "Healthcare & Medical",
  "internal_medicine": "Healthcare & Medical",
  "psychologist": "Healthcare & Medical",
  "traditional_chinese_medicine": "Healthcare & Medical",
  "nursing_school": "Healthcare & Medical",
  "health_retreats": "Healthcare & Medical",
  "occupational_therapy": "Healthcare & Medical",
  "speech_therapist": "Healthcare & Medical",
  "veterinarian": "Healthcare & Medical",
  "allergist": "Healthcare & Medical",
  "counseling_and_mental_health": "Healthcare & Medical",
  "chiropractor": "Healthcare & Medical",
  "endocrinologist": "Healthcare & Medical",
  "dental_supply_store": "Healthcare & Medical",
  "pathologist": "Healthcare & Medical",
  "pediatrician": "Healthcare & Medical",
  "health_department": "Healthcare & Medical",
  "oral_surgeon": "Healthcare & Medical",
  "rheumatologist": "Healthcare & Medical",
  "surgeon": "Healthcare & Medical",
  "maternity_wear": "Healthcare & Medical",
  "cosmetic_surgeon": "Healthcare & Medical",
  "geriatric_medicine": "Healthcare & Medical",
  "abortion_clinic": "Healthcare & Medical",
  "orthopedist": "Healthcare & Medical",
  "sex_therapist": "Healthcare & Medical",
  "medical_sciences_schools": "Healthcare & Medical",
  "medical_research_and_development": "Healthcare & Medical",
  "doctor": "Healthcare & Medical",
  "animal_assisted_therapy": "Healthcare & Medical",
  "urgent_care_clinic": "Healthcare & Medical",
  "ophthalmologist": "Healthcare & Medical",
  "neuropathologist": "Healthcare & Medical",
  "toxicologist": "Healthcare & Medical",
  "medical_spa": "Healthcare & Medical",
  "sperm_clinic": "Healthcare & Medical",
  "sports_medicine": "Healthcare & Medical",
  "dentist": "Healthcare & Medical",
  "health_insurance_office": "Healthcare & Medical",
  "osteopathic_physician": "Healthcare & Medical",
  "hypnosis_hypnotherapy": "Healthcare & Medical",
  "pediatric_oncology": "Healthcare & Medical",
  "prenatal_perinatal_care": "Healthcare & Medical",
  "dental_hygienist": "Healthcare & Medical",
  "acupuncture": "Healthcare & Medical",
  "pharmacy_schools": "Healthcare & Medical",
  "cryotherapy": "Healthcare & Medical",
  "hospice": "Healthcare & Medical",
  "hematology": "Healthcare & Medical",
  "hospitalist": "Healthcare & Medical",
  "plastic_surgeon": "Healthcare & Medical",
  "clinical_laboratories": "Healthcare & Medical",
  "audiologist": "Healthcare & Medical",
  "health_spa": "Healthcare & Medical",
  "marriage_or_relationship_counselor": "Healthcare & Medical",
  "pediatric_cardiology": "Healthcare & Medical",
  "walk_in_clinic": "Healthcare & Medical",
  "nephrologist": "Healthcare & Medical",
  "dialysis_clinic": "Healthcare & Medical",
  "immunodermatologist": "Healthcare & Medical",
  "emergency_room": "Healthcare & Medical",
  "pediatric_nephrology": "Healthcare & Medical",
  "emergency_pet_hospital": "Healthcare & Medical",
  "cannabis_clinic": "Healthcare & Medical",
  "medical_transportation": "Healthcare & Medical",
  "concierge_medicine": "Healthcare & Medical",
  "medical_law": "Healthcare & Medical",
  "skilled_nursing": "Healthcare & Medical",
  "hydrotherapy": "Healthcare & Medical",
  "neurologist": "Healthcare & Medical",
  "massage_therapy": "Healthcare & Medical",
  "cardiovascular_and_thoracic_surgeon": "Healthcare & Medical",
  "medical_service_organizations": "Healthcare & Medical",
  "health_consultant": "Healthcare & Medical",
  "health_and_wellness_club": "Healthcare & Medical",
  "psychotherapist": "Healthcare & Medical",
  "pet_hospice": "Healthcare & Medical",
  "pharmacy": "Healthcare & Medical",
  "psychiatrist": "Healthcare & Medical",
  "laser_eye_surgery_lasik": "Healthcare & Medical",
  "eye_care_clinic": "Healthcare & Medical",
  "obstetrician_and_gynecologist": "Healthcare & Medical",
  "dermatologist": "Healthcare & Medical",
  "naturopathic_holistic": "Healthcare & Medical",
  "hospital_equipment_and_supplies": "Healthcare & Medical",
  "acne_treatment": "Healthcare & Medical",
  "podiatrist": "Healthcare & Medical",
  "dentistry_schools": "Healthcare & Medical",
  "home_health_care": "Healthcare & Medical",
  "hospital": "Healthcare & Medical",
  "holistic_animal_care": "Healthcare & Medical",
  "pediatric_anesthesiology": "Healthcare & Medical",
  "medical_school": "Healthcare & Medical",
  "preventive_medicine": "Healthcare & Medical",
  "childrens_hospital": "Healthcare & Medical",
  "environmental_medicine": "Healthcare & Medical",
  "child_psychiatrist": "Healthcare & Medical",
  "medical_cannabis_referral": "Healthcare & Medical",
  "pediatric_endocrinology": "Healthcare & Medical",
  "addiction_rehabilitation_center": "Healthcare & Medical",
  "neurotologist": "Healthcare & Medical",
  "animal_physical_therapy": "Healthcare & Medical",
  "homeopathic_medicine": "Healthcare & Medical",
  "gardener": "Home & Garden Services",
  "air_duct_cleaning_service": "Home & Garden Services",
  "industrial_cleaning_services": "Home & Garden Services",
  "deck_and_railing_sales_service": "Home & Garden Services",
  "key_and_locksmith": "Home & Garden Services",
  "carpet_cleaning": "Home & Garden Services",
  "garage_door_service": "Home & Garden Services",
  "gutter_service": "Home & Garden Services",
  "junk_removal_and_hauling": "Home & Garden Services",
  "cleaning_products_supplier": "Home & Garden Services",
  "cleaning_services": "Home & Garden Services",
  "pressure_washing": "Home & Garden Services",
  "indoor_landscaping": "Home & Garden Services",
  "chimney_service": "Home & Garden Services",
  "handyman": "Home & Garden Services",
  "solar_panel_cleaning": "Home & Garden Services",
  "movers": "Home & Garden Services",
  "patio_covers": "Home & Garden Services",
  "chimney_sweep": "Home & Garden Services",
  "dry_cleaning": "Home & Garden Services",
  "tree_services": "Home & Garden Services",
  "snow_removal_service": "Home & Garden Services",
  "landscaping": "Home & Garden Services",
  "pool_cleaning": "Home & Garden Services",
  "office_cleaning": "Home & Garden Services",
  "security_systems": "Home & Garden Services",
  "fence_and_gate_sales_service": "Home & Garden Services",
  "window_washing": "Home & Garden Services",
  "janitorial_services": "Home & Garden Services",
  "home_cleaning": "Home & Garden Services",
  "occupational_safety": "Home & Garden Services",
  "pest_control_service": "Home & Garden Services",
  "metal_detector_services": "Manufacturing & Industrial",
  "jewelry_manufacturer": "Manufacturing & Industrial",
  "mining": "Manufacturing & Industrial",
  "printing_equipment_and_supply": "Manufacturing & Industrial",
  "b2b_storage_and_warehouses": "Manufacturing & Industrial",
  "shoe_factory": "Manufacturing & Industrial",
  "plastic_company": "Manufacturing & Industrial",
  "chemical_plant": "Manufacturing & Industrial",
  "oil_and_gas_exploration_and_development": "Manufacturing & Industrial",
  "book_magazine_distribution": "Manufacturing & Industrial",
  "b2b_textiles": "Manufacturing & Industrial",
  "metals": "Manufacturing & Industrial",
  "printing_services": "Manufacturing & Industrial",
  "b2b_rubber_and_plastics": "Manufacturing & Industrial",
  "coal_and_coke": "Manufacturing & Industrial",
  "iron_work": "Manufacturing & Industrial",
  "mattress_manufacturing": "Manufacturing & Industrial",
  "scrap_metals": "Manufacturing & Industrial",
  "business_manufacturing_and_supply": "Manufacturing & Industrial",
  "environmental_renewable_natural_resource": "Manufacturing & Industrial",
  "industrial_spares_and_products_wholesaler": "Manufacturing & Industrial",
  "aircraft_manufacturer": "Manufacturing & Industrial",
  "lighting_fixture_manufacturers": "Manufacturing & Industrial",
  "glass_manufacturer": "Manufacturing & Industrial",
  "oil_and_gas_field_equipment_and_services": "Manufacturing & Industrial",
  "saw_mill": "Manufacturing & Industrial",
  "appliance_manufacturer": "Manufacturing & Industrial",
  "manufacturers_agents_and_representatives": "Manufacturing & Industrial",
  "leather_products_manufacturer": "Manufacturing & Industrial",
  "industrial_company": "Manufacturing & Industrial",
  "mills": "Manufacturing & Industrial",
  "textile_mill": "Manufacturing & Industrial",
  "oil_and_gas": "Manufacturing & Industrial",
  "environmental_abatement_services": "Manufacturing & Industrial",
  "industrial_equipment": "Manufacturing & Industrial",
  "plastic_fabrication_company": "Manufacturing & Industrial",
  "iron_and_steel_industry": "Manufacturing & Industrial",
  "furniture_assembly": "Manufacturing & Industrial",
  "sheet_metal": "Manufacturing & Industrial",
  "flour_mill": "Manufacturing & Industrial",
  "distribution_services": "Manufacturing & Industrial",
  "steel_fabricators": "Manufacturing & Industrial",
  "environmental_and_ecological_services_for_businesses": "Manufacturing & Industrial",
  "metal_supplier": "Manufacturing & Industrial",
  "fingerprinting_service": "Manufacturing & Industrial",
  "environmental_conservation_organization": "Manufacturing & Industrial",
  "cosmetic_products_manufacturer": "Manufacturing & Industrial",
  "metal_plating_service": "Manufacturing & Industrial",
  "screen_printing_t_shirt_printing": "Manufacturing & Industrial",
  "environmental_testing": "Manufacturing & Industrial",
  "paper_mill": "Manufacturing & Industrial",
  "wallpaper_installers": "Manufacturing & Industrial",
  "jewelry_and_watches_manufacturer": "Manufacturing & Industrial",
  "furniture_manufacturers": "Manufacturing & Industrial",
  "3d_printing_service": "Manufacturing & Industrial",
  "commercial_industrial": "Manufacturing & Industrial",
  "plastic_manufacturer": "Manufacturing & Industrial",
  "warehouses": "Manufacturing & Industrial",
  "environmental_conservation_and_ecological_organizations": "Manufacturing & Industrial",
  "cotton_mill": "Manufacturing & Industrial",
  "metal_materials_and_experts": "Manufacturing & Industrial",
  "b2b_oil_and_gas_extraction_and_services": "Manufacturing & Industrial",
  "metal_fabricator": "Manufacturing & Industrial",
  "social_media_company": "Media & Communications",
  "media_news_company": "Media & Communications",
  "radio_station": "Media & Communications",
  "print_media": "Media & Communications",
  "media_news_website": "Media & Communications",
  "television_station": "Media & Communications",
  "mass_media": "Media & Communications",
  "media_critic": "Media & Communications",
  "business_to_business_services": "Other Services",
  "shades_and_blinds": "Other Services",
  "tabletop_games": "Other Services",
  "farm_equipment_and_supply": "Other Services",
  "books_mags_music_and_video": "Other Services",
  "gemstone_and_mineral": "Other Services",
  "infectious_disease_specialist": "Other Services",
  "oil_refiners": "Other Services",
  "information_technology_company": "Other Services",
  "shoe_shining_service": "Other Services",
  "office_equipment": "Other Services",
  "packing_services": "Other Services",
  "ticket_sales": "Other Services",
  "bus_rentals": "Other Services",
  "iv_hydration": "Healthcare & Medical",
  "racing_experience": "Other Services",
  "land_surveying": "Other Services",
  "ear_nose_and_throat": "Healthcare & Medical",
  "water_purification_services": "Other Services",
  "scientific_laboratories": "Healthcare & Medical",
  "teeth_whitening": "Healthcare & Medical",
  "marina": "Other Services",
  "door_sales_service": "Other Services",
  "cannabis_collective": "Other Services",
  "road_structures_and_services": "Other Services",
  "canal": "Other Services",
  "travel_company": "Other Services",
  "firewood": "Other Services",
  "jazz_and_blues": "Arts & Entertainment",
  "antenna_service": "Other Services",
  "rest_areas": "Other Services",
  "laser_cutting_service_provider": "Other Services",
  "elevator_service": "Other Services",
  "orthodontist": "Healthcare & Medical",
  "business_equipment_and_supply": "Business-to-Business",
  "pedicab_service": "Other Services",
  "personal_care_service": "Other Services",
  "paint_your_own_pottery": "Other Services",
  "exhibition_and_trade_center": "Other Services",
  "safety_equipment": "Other Services",
  "writing_service": "Other Services",
  "prosthodontist": "Healthcare & Medical",
  "security_services": "Other Services",
  "laundromat": "Other Services",
  "country_club": "Other Services",
  "backpacking_area": "Other Services",
  "music_critic": "Arts & Entertainment",
  "feng_shui": "Home & Garden Services",
  "holiday_decor": "Home & Garden Services",
  "endodontist": "Healthcare & Medical",
  "bulk_billing": "Other Services",
  "sign_making": "Other Services",
  "luggage_storage": "Other Services",
  "vitamins_and_supplements": "Other Services",
  "team_building_activity": "Other Services",
  "street_vendor": "Other Services",
  "general_litigation": "Other Services",
  "foot_care": "Healthcare & Medical",
  "logging_equipment_and_supplies": "Other Services",
  "freight_and_cargo_service": "Other Services",
  "meat_wholesaler": "Other Services",
  "pool_hall": "Other Services",
  "windows_installation": "Construction & Contractors",
  "horseback_riding_service": "Other Services",
  "fidelity_and_surety_bonds": "Financial Services",
  "genealogists": "Other Services",
  "emergency_roadside_service": "Other Services",
  "payroll_services": "Financial Services",
  "plaza": "Other Services",
  "business_financing": "Financial Services",
  "supernatural_reading": "Other Services",
  "solar_installation": "Construction & Contractors",
  "glass_and_mirror_sales_service": "Other Services",
  "inventory_control_service": "Other Services",
  "ev_charging_station": "Other Services",
  "footwear_wholesaler": "Other Services",
  "translating_and_interpreting_services": "Other Services",
  "family_practice": "Healthcare & Medical",
  "wine_tasting_room": "Other Services",
  "private_jet_charters": "Other Services",
  "auction_house": "Other Services",
  "mobility_equipment_services": "Healthcare & Medical",
  "active_life": "Healthcare & Medical",
  "misting_system_services": "Other Services",
  "hearing_aids": "Healthcare & Medical",
  "nudist_clubs": "Other Services",
  "scooter_rental": "Other Services",
  "bags_luggage_company": "Other Services",
  "challenge_courses_center": "Other Services",
  "package_locker": "Other Services",
  "bike_sharing": "Other Services",
  "ceiling_service": "Other Services",
  "halfway_house": "Other Services",
  "sandblasting_service": "Other Services",
  "arts_and_crafts": "Other Services",
  "embroidery_and_crochet": "Other Services",
  "betting_center": "Other Services",
  "olive_oil": "Other Services",
  "quay": "Other Services",
  "plasterer": "Other Services",
  "wholesale_grocer": "Other Services",
  "sleep_specialist": "Healthcare & Medical",
  "bookmakers": "Other Services",
  "business_to_business": "Business-to-Business",
  "fishmonger": "Other Services",
  "artificial_turf": "Other Services",
  "jet_skis_rental": "Other Services",
  "countertop_installation": "Construction & Contractors",
  "musician": "Arts & Entertainment",
  "immigration_assistance_services": "Other Services",
  "gold_buyer": "Other Services",
  "motor_freight_trucking": "Other Services",
  "promotional_products_and_services": "Other Services",
  "street_art": "Arts & Entertainment",
  "kitchen_and_bath": "Construction & Contractors",
  "display_home_center": "Other Services",
  "quarries": "Other Services",
  "hearing_aid_provider": "Healthcare & Medical",
  "skylight_installation": "Construction & Contractors",
  "tower_communication_service": "Other Services",
  "corporate_office": "Other Services",
  "rv_storage_facility": "Other Services",
  "smokehouse": "Other Services",
  "archaeological_services": "Other Services",
  "golf_equipment": "Retail & Shopping",
  "tea_wholesaler": "Other Services",
  "courier_and_delivery_services": "Other Services",
  "ultrasound_imaging_center": "Healthcare & Medical",
  "cemeteries": "Other Services",
  "prosthetics": "Healthcare & Medical",
  "tui_na": "Other Services",
  "organ_and_tissue_donor_service": "Healthcare & Medical",
  "bike_rentals": "Other Services",
  "shutters": "Other Services",
  "radio_and_television_commercials": "Other Services",
  "private_equity_firm": "Financial Services",
  "holding_companies": "Other Services",
  "logging_services": "Other Services",
  "hot_air_balloons_tour": "Other Services",
  "interlock_system": "Other Services",
  "tools_wholesaler": "Other Services",
  "ambulance_and_ems_services": "Healthcare & Medical",
  "cheerleading": "Other Services",
  "leather_goods": "Other Services",
  "geological_services": "Other Services",
  "tv_mounting": "Other Services",
  "weather_forecast_services": "Other Services",
  "phlebologist": "Other Services",
  "travel_services": "Other Services",
  "video_and_video_game_rentals": "Other Services",
  "shipping_collection_services": "Other Services",
  "mortuary_services": "Other Services",
  "private_investigation": "Other Services",
  "fmcg_wholesaler": "Other Services",
  "tower": "Other Services",
  "strip_club": "Other Services",
  "paint_and_sip": "Other Services",
  "laboratory": "Healthcare & Medical",
  "pool_and_billiards": "Other Services",
  "geriatric_psychiatry": "Healthcare & Medical",
  "business": "Other Services",
  "money_transfer_services": "Financial Services",
  "home_service": "Other Services",
  "surgical_appliances_and_supplies": "Healthcare & Medical",
  "digitizing_services": "Other Services",
  "drinking_water_dispenser": "Other Services",
  "furniture_wholesalers": "Other Services",
  "computer_hardware_company": "Other Services",
  "dance_wear": "Other Services",
  "session_photography": "Arts & Entertainment",
  "house_sitting": "Other Services",
  "mailbox_center": "Other Services",
  "gerontologist": "Healthcare & Medical",
  "holiday_rental_home": "Other Services",
  "wood_and_pulp": "Other Services",
  "props": "Other Services",
  "casting_molding_and_machining": "Other Services",
  "osteopath": "Healthcare & Medical",
  "bottled_water_company": "Other Services",
  "wellness_program": "Healthcare & Medical",
  "process_servers": "Other Services",
  "lottery_ticket": "Other Services",
  "cremation_services": "Other Services",
  "self_storage_facility": "Other Services",
  "crane_services": "Other Services",
  "billing_services": "Other Services",
  "duplication_services": "Other Services",
  "fencing_club": "Other Services",
  "packing_supply": "Other Services",
  "refinishing_services": "Other Services",
  "officiating_services": "Other Services",
  "indoor_playcenter": "Other Services",
  "nurse_practitioner": "Healthcare & Medical",
  "structure_and_geography": "Other Services",
  "knife_sharpening": "Other Services",
  "baby_gear_and_furniture": "Other Services",
  "fruits_and_vegetables": "Other Services",
  "pets": "Other Services",
  "party_supply": "Other Services",
  "collection_agencies": "Financial Services",
  "event_photography": "Arts & Entertainment",
  "international_business_and_trade_services": "Other Services",
  "pool_billiards": "Other Services",
  "trivia_host": "Other Services",
  "pier": "Other Services",
  "travel": "Other Services",
  "driving_range": "Other Services",
  "piano_services": "Other Services",
  "fire_protection_service": "Other Services",
  "irrigation": "Other Services",
  "goldsmith": "Other Services",
  "hot_tubs_and_pools": "Other Services",
  "farrier_services": "Other Services",
  "fireplace_service": "Other Services",
  "hang_gliding_center": "Other Services",
  "water_delivery": "Other Services",
  "test_preparation": "Other Services",
  "christmas_trees": "Other Services",
  "background_check_services": "Other Services",
  "family_service_center": "Other Services",
  "behavior_analyst": "Other Services",
  "child_protection_service": "Other Services",
  "surgical_center": "Other Services",
  "country_house": "Other Services",
  "irrigation_companies": "Other Services",
  "typing_services": "Other Services",
  "pool_and_hot_tub_services": "Other Services",
  "event_technology_service": "Other Services",
  "investing": "Other Services",
  "pharmaceutical_companies": "Other Services",
  "assisted_living_facility": "Other Services",
  "audiovisual_equipment_rental": "Other Services",
  "holiday_decorating": "Other Services",
  "hydro_jetting": "Other Services",
  "wine_wholesaler": "Other Services",
  "pharmaceutical_products_wholesaler": "Other Services",
  "psychoanalyst": "Healthcare & Medical",
  "storage_facility": "Other Services",
  "endoscopist": "Healthcare & Medical",
  "orthotics": "Healthcare & Medical",
  "chocolatier": "Other Services",
  "home_decor": "Other Services",
  "diagnostic_imaging": "Healthcare & Medical",
  "nanny_services": "Other Services",
  "bookbinding": "Other Services",
  "chambers_of_commerce": "Other Services",
  "travel_agents": "Tourism & Attractions",
  "macarons": "Other Services",
  "placenta_encapsulation_service": "Healthcare & Medical",
  "grout_service": "Other Services",
  "body_contouring": "Other Services",
  "shipping_center": "Other Services",
  "weather_station": "Other Services",
  "rv_rentals": "Other Services",
  "bus_service": "Transportation",
  "linen": "Other Services",
  "dumpster_rentals": "Other Services",
  "computer_wholesaler": "Other Services",
  "skyscraper": "Other Services",
  "hockey_equipment": "Other Services",
  "laboratory_testing": "Healthcare & Medical",
  "podiatry": "Healthcare & Medical",
  "social_and_human_services": "Other Services",
  "grilling_equipment": "Other Services",
  "periodontist": "Healthcare & Medical",
  "mobile_phone_accessories": "Other Services",
  "merchandising_service": "Other Services",
  "record_label": "Other Services",
  "blacksmiths": "Other Services",
  "aircraft_parts_and_supplies": "Other Services",
  "calligraphy": "Other Services",
  "television_service_providers": "Other Services",
  "memory_care": "Other Services",
  "registry_office": "Other Services",
  "rest_stop": "Other Services",
  "auditorium": "Other Services",
  "musical_instrument_services": "Other Services",
  "sugar_shack": "Other Services",
  "club_crawl": "Other Services",
  "home_security": "Other Services",
  "traffic_school": "Other Services",
  "rv_and_boat_storage_facility": "Other Services",
  "boat_parts_and_accessories": "Other Services",
  "marble_and_granite_professionals": "Other Services",
  "blueprinters": "Other Services",
  "junkyard": "Other Services",
  "cannabis_tour": "Other Services",
  "boat_storage_facility": "Other Services",
  "salsa_club": "Other Services",
  "funeral_services_and_cemeteries": "Other Services",
  "lighting_fixtures_and_equipment": "Other Services",
  "campus_building": "Other Services",
  "canteen": "Other Services",
  "paternity_tests_and_services": "Healthcare & Medical",
  "roadside_assistance": "Other Services",
  "ziplining_center": "Other Services",
  "kids_recreation_and_party": "Other Services",
  "immigration_and_naturalization": "Government & Public Services",
  "onsen": "Other Services",
  "high_gliding_center": "Other Services",
  "shredding_services": "Other Services",
  "wills_trusts_and_probate": "Other Services",
  "greenhouses": "Other Services",
  "gunsmith": "Other Services",
  "business_signage": "Other Services",
  "glass_blowing": "Other Services",
  "secretarial_services": "Other Services",
  "trusts": "Other Services",
  "wholesaler": "Other Services",
  "colonics": "Healthcare & Medical",
  "sommelier_service": "Other Services",
  "customized_merchandise": "Other Services",
  "eatertainment": "Other Services",
  "country_dance_hall": "Other Services",
  "snorkeling_equipment_rental": "Other Services",
  "commercial_refrigeration": "Other Services",
  "boat_charter": "Other Services",
  "powder_coating_service": "Other Services",
  "commercial_printer": "Other Services",
  "escrow_services": "Other Services",
  "reflexology": "Other Services",
  "fabric_wholesaler": "Other Services",
  "e_commerce_service": "Other Services",
  "trains": "Other Services",
  "backflow_services": "Other Services",
  "bicycle_path": "Other Services",
  "diagnostic_services": "Other Services",
  "fashion": "Other Services",
  "private_tutor": "Other Services",
  "tobacco_company": "Other Services",
  "caricature": "Other Services",
  "lingerie_wholesaler": "Other Services",
  "copywriting_service": "Other Services",
  "kitchen_incubator": "Other Services",
  "business_office_supplies_and_stationery": "Other Services",
  "machine_and_tool_rentals": "Other Services",
  "stucco_services": "Other Services",
  "professional_services": "Professional Services",
  "driving_school": "Other Services",
  "social_club": "Other Services",
  "island": "Parks & Natural Features",
  "playground": "Parks & Natural Features",
  "desert": "Parks & Natural Features",
  "nursery_and_gardening": "Parks & Natural Features",
  "canyon": "Parks & Natural Features",
  "forest": "Parks & Natural Features",
  "lake": "Parks & Natural Features",
  "waterfall": "Parks & Natural Features",
  "hot_springs": "Parks & Natural Features",
  "beach": "Parks & Natural Features",
  "cave": "Parks & Natural Features",
  "mountain": "Parks & Natural Features",
  "nature_reserve": "Parks & Natural Features",
  "national_park": "Parks & Natural Features",
  "forestry_service": "Parks & Natural Features",
  "mobile_home_park": "Parks & Natural Features",
  "atv_recreation_park": "Parks & Natural Features",
  "sand_dune": "Parks & Natural Features",
  "hydroponic_gardening": "Parks & Natural Features",
  "home_and_garden": "Parks & Natural Features",
  "wildlife_control": "Parks & Natural Features",
  "playground_equipment_supplier": "Parks & Natural Features",
  "park_and_rides": "Parks & Natural Features",
  "park": "Parks & Natural Features",
  "beer_garden": "Parks & Natural Features",
  "beach_equipment_rentals": "Parks & Natural Features",
  "natural_hot_springs": "Parks & Natural Features",
  "holiday_park": "Parks & Natural Features",
  "river": "Parks & Natural Features",
  "community_gardens": "Parks & Natural Features",
  "wildlife_sanctuary": "Parks & Natural Features",
  "dog_park": "Parks & Natural Features",
  "spring_supplier": "Parks & Natural Features",
  "personal_chef": "Personal Services",
  "laundry_services": "Personal Services",
  "sewing_and_alterations": "Personal Services",
  "valet_service": "Personal Services",
  "gents_tailor": "Personal Services",
  "personal_assistant": "Personal Services",
  "matchmaker": "Personal Services",
  "engraving": "Personal Services",
  "pet_photography": "Pet Services",
  "homeless_shelter": "Pet Services",
  "animal_shelter": "Pet Services",
  "pet_adoption": "Pet Services",
  "animal_rescue_service": "Pet Services",
  "pet_sitting": "Pet Services",
  "pet_services": "Pet Services",
  "pet_breeder": "Pet Services",
  "adoption_services": "Pet Services",
  "pet_cemetery_and_crematorium_services": "Pet Services",
  "pet_boarding": "Pet Services",
  "dog_walkers": "Pet Services",
  "flyboarding_center": "Pet Services",
  "carpet_installation": "Pet Services",
  "pet_groomer": "Pet Services",
  "flyboarding_rental": "Pet Services",
  "appellate_practice_lawyers": "Professional Services",
  "unemployment_office": "Professional Services",
  "construction_management": "Professional Services",
  "pain_management": "Healthcare & Medical",
  "business_management_services": "Professional Services",
  "divorce_and_family_law": "Professional Services",
  "forestry_consultants": "Professional Services",
  "traffic_ticketing_law": "Professional Services",
  "translation_services": "Professional Services",
  "architect": "Professional Services",
  "engineering_services": "Professional Services",
  "lawyer": "Professional Services",
  "architectural_designer": "Professional Services",
  "paralegal_services": "Professional Services",
  "civil_rights_lawyers": "Professional Services",
  "architectural_tours": "Professional Services",
  "workers_compensation_law": "Professional Services",
  "accountant": "Professional Services",
  "financial_advising": "Professional Services",
  "photographer": "Professional Services",
  "dui_law": "Professional Services",
  "business_consulting": "Professional Services",
  "videographer": "Professional Services",
  "web_designer": "Professional Services",
  "advertising_agency": "Professional Services",
  "employment_agencies": "Professional Services",
  "bookkeeper": "Professional Services",
  "graphic_designer": "Professional Services",
  "criminal_defense_law": "Professional Services",
  "human_resource_services": "Professional Services",
  "lawn_service": "Professional Services",
  "business_law": "Professional Services",
  "business_advertising": "Professional Services",
  "tax_law": "Professional Services",
  "patent_law": "Professional Services",
  "civil_engineers": "Professional Services",
  "acoustical_consultant": "Professional Services",
  "personal_injury_law": "Professional Services",
  "temp_agency": "Professional Services",
  "direct_mail_advertising": "Professional Services",
  "it_consultant": "Professional Services",
  "structural_engineer": "Professional Services",
  "product_design": "Professional Services",
  "law_enforcement": "Professional Services",
  "business_records_storage_and_management": "Professional Services",
  "architecture": "Professional Services",
  "agricultural_engineering_service": "Professional Services",
  "real_estate_law": "Professional Services",
  "tenant_and_eviction_law": "Professional Services",
  "energy_management_and_conservation_consultants": "Professional Services",
  "consultant_and_general_service": "Professional Services",
  "manufacturing_and_industrial_consultant": "Professional Services",
  "ip_and_internet_law": "Professional Services",
  "bankruptcy_law": "Professional Services",
  "outdoor_advertising": "Professional Services",
  "transcription_services": "Professional Services",
  "property_management": "Professional Services",
  "b2b_cleaning_and_waste_management": "Professional Services",
  "financial_service": "Professional Services",
  "interior_design": "Professional Services",
  "image_consultant": "Professional Services",
  "legal_services": "Professional Services",
  "employment_law": "Professional Services",
  "social_security_law": "Professional Services",
  "floral_designer": "Professional Services",
  "stress_management_services": "Professional Services",
  "instrumentation_engineers": "Professional Services",
  "tax_services": "Professional Services",
  "appraisal_services": "Professional Services",
  "exterior_design": "Professional Services",
  "immigration_law": "Professional Services",
  "editorial_services": "Professional Services",
  "landscape_architect": "Professional Services",
  "contract_law": "Professional Services",
  "executive_search_consultants": "Professional Services",
  "disability_law": "Professional Services",
  "estate_planning_law": "Professional Services",
  "mediator": "Professional Services",
  "home_inspector": "Real Estate",
  "real_estate_photography": "Real Estate",
  "home_developer": "Real Estate",
  "real_estate_agent": "Real Estate",
  "commercial_real_estate": "Real Estate",
  "real_estate_service": "Real Estate",
  "home_staging": "Real Estate",
  "real_estate": "Real Estate",
  "episcopal_church": "Religious & Spiritual",
  "pentecostal_church": "Religious & Spiritual",
  "church_cathedral": "Religious & Spiritual",
  "synagogue": "Religious & Spiritual",
  "religious_organization": "Religious & Spiritual",
  "mystic": "Religious & Spiritual",
  "catholic_church": "Religious & Spiritual",
  "jehovahs_witness_kingdom_hall": "Religious & Spiritual",
  "religious_items": "Religious & Spiritual",
  "mosque": "Religious & Spiritual",
  "psychic": "Religious & Spiritual",
  "sikh_temple": "Religious & Spiritual",
  "astrologer": "Religious & Spiritual",
  "evangelical_church": "Religious & Spiritual",
  "buddhist_temple": "Religious & Spiritual",
  "temple": "Religious & Spiritual",
  "hindu_temple": "Religious & Spiritual",
  "baptist_church": "Religious & Spiritual",
  "religious_destination": "Religious & Spiritual",
  "wedding_chapel": "Religious & Spiritual",
  "anglican_church": "Religious & Spiritual",
  "convents_and_monasteries": "Religious & Spiritual",
  "meditation_center": "Religious & Spiritual",
  "mission": "Religious & Spiritual",
  "psychic_medium": "Religious & Spiritual",
  "hardware_store": "Retail & Shopping",
  "thrift_store": "Retail & Shopping",
  "threads_and_yarns_wholesaler": "Retail & Shopping",
  "home_theater_systems_stores": "Retail & Shopping",
  "kiosk": "Retail & Shopping",
  "aquatic_pet_store": "Retail & Shopping",
  "sunglasses_store": "Retail & Shopping",
  "furniture_accessory_store": "Retail & Shopping",
  "convenience_store": "Retail & Shopping",
  "clothing_company": "Retail & Shopping",
  "outdoor_gear": "Retail & Shopping",
  "formal_wear_store": "Retail & Shopping",
  "flea_market": "Retail & Shopping",
  "orthopedic_shoe_store": "Retail & Shopping",
  "ethical_grocery": "Retail & Shopping",
  "childrens_clothing_store": "Retail & Shopping",
  "fur_clothing": "Retail & Shopping",
  "grocery_store": "Retail & Shopping",
  "welding_supply_store": "Retail & Shopping",
  "building_supply_store": "Retail & Shopping",
  "marketing_agency": "Retail & Shopping",
  "kosher_grocery_store": "Retail & Shopping",
  "b2b_apparel": "Retail & Shopping",
  "plus_size_clothing": "Retail & Shopping",
  "car_stereo_store": "Retail & Shopping",
  "lawn_mower_store": "Retail & Shopping",
  "pet_store": "Retail & Shopping",
  "rug_store": "Retail & Shopping",
  "tire_repair_shop": "Retail & Shopping",
  "retail": "Retail & Shopping",
  "asian_grocery_store": "Retail & Shopping",
  "online_shop": "Retail & Shopping",
  "duty_free_shop": "Retail & Shopping",
  "womens_clothing_store": "Retail & Shopping",
  "paint_store": "Retail & Shopping",
  "framing_store": "Retail & Shopping",
  "swimwear_store": "Retail & Shopping",
  "window_treatment_store": "Retail & Shopping",
  "gift_shop": "Retail & Shopping",
  "discount_store": "Retail & Shopping",
  "photography_store_and_services": "Retail & Shopping",
  "home_improvement_store": "Retail & Shopping",
  "mattress_store": "Retail & Shopping",
  "supermarket": "Retail & Shopping",
  "reptile_shop": "Retail & Shopping",
  "spiritual_shop": "Retail & Shopping",
  "pawn_shop": "Retail & Shopping",
  "machine_shop": "Retail & Shopping",
  "japanese_confectionery_shop": "Retail & Shopping",
  "water_store": "Retail & Shopping",
  "internet_marketing_service": "Retail & Shopping",
  "lumber_store": "Retail & Shopping",
  "outdoor_furniture_store": "Retail & Shopping",
  "wholesale_store": "Retail & Shopping",
  "night_market": "Retail & Shopping",
  "fertilizer_store": "Retail & Shopping",
  "ceremonial_clothing": "Retail & Shopping",
  "fashion_accessories_store": "Retail & Shopping",
  "surf_shop": "Retail & Shopping",
  "art_supply_store": "Retail & Shopping",
  "army_and_navy_store": "Retail & Shopping",
  "academic_bookstore": "Retail & Shopping",
  "flower_markets": "Retail & Shopping",
  "carpet_store": "Retail & Shopping",
  "eyewear_and_optician": "Retail & Shopping",
  "boat_parts_and_supply_store": "Retail & Shopping",
  "audio_visual_equipment_store": "Retail & Shopping",
  "outlet_store": "Retail & Shopping",
  "farmers_market": "Retail & Shopping",
  "custom_t_shirt_store": "Retail & Shopping",
  "hair_supply_stores": "Retail & Shopping",
  "denim_wear_store": "Retail & Shopping",
  "uniform_store": "Retail & Shopping",
  "musical_instrument_store": "Retail & Shopping",
  "gun_and_ammo": "Retail & Shopping",
  "traditional_clothing": "Retail & Shopping",
  "dive_shop": "Retail & Shopping",
  "music_and_dvd_store": "Retail & Shopping",
  "luggage_store": "Retail & Shopping",
  "mexican_grocery_store": "Retail & Shopping",
  "optical_wholesaler": "Retail & Shopping",
  "skate_shop": "Retail & Shopping",
  "toy_store": "Retail & Shopping",
  "tobacco_shop": "Retail & Shopping",
  "personal_shopper": "Retail & Shopping",
  "liquor_store": "Retail & Shopping",
  "diy_auto_shop": "Retail & Shopping",
  "jewelry_store": "Retail & Shopping",
  "shoe_store": "Retail & Shopping",
  "international_grocery_store": "Retail & Shopping",
  "piano_store": "Retail & Shopping",
  "hobby_shop": "Retail & Shopping",
  "herbal_shop": "Retail & Shopping",
  "used_vintage_and_consignment": "Retail & Shopping",
  "newspaper_and_magazines_store": "Retail & Shopping",
  "bridal_shop": "Retail & Shopping",
  "honey_farm_shop": "Retail & Shopping",
  "mobile_phone_store": "Retail & Shopping",
  "boutique": "Retail & Shopping",
  "firework_retailer": "Retail & Shopping",
  "guitar_store": "Retail & Shopping",
  "specialty_grocery_store": "Retail & Shopping",
  "indian_grocery_store": "Retail & Shopping",
  "flowers_and_gifts_shop": "Retail & Shopping",
  "telemarketing_services": "Retail & Shopping",
  "knitting_supply": "Retail & Shopping",
  "korean_grocery_store": "Retail & Shopping",
  "brewing_supply_store": "Retail & Shopping",
  "lighting_store": "Retail & Shopping",
  "trophy_shop": "Retail & Shopping",
  "herb_and_spice_shop": "Retail & Shopping",
  "flooring_store": "Retail & Shopping",
  "comic_books_store": "Retail & Shopping",
  "russian_grocery_store": "Retail & Shopping",
  "vinyl_record_store": "Retail & Shopping",
  "auto_parts_and_supply_store": "Retail & Shopping",
  "pen_store": "Retail & Shopping",
  "handicraft_shop": "Retail & Shopping",
  "designer_clothing": "Retail & Shopping",
  "bookstore": "Retail & Shopping",
  "perfume_store": "Retail & Shopping",
  "plastic_injection_molding_workshop": "Retail & Shopping",
  "woodworking_supply_store": "Retail & Shopping",
  "agricultural_seed_store": "Retail & Shopping",
  "craft_shop": "Retail & Shopping",
  "japanese_grocery_store": "Retail & Shopping",
  "appliance_store": "Retail & Shopping",
  "beverage_store": "Retail & Shopping",
  "electronics_repair_shop": "Retail & Shopping",
  "bathroom_fixture_stores": "Retail & Shopping",
  "candle_store": "Retail & Shopping",
  "tire_shop": "Retail & Shopping",
  "watch_store": "Retail & Shopping",
  "computer_store": "Retail & Shopping",
  "farming_equipment_store": "Retail & Shopping",
  "cannabis_dispensary": "Retail & Shopping",
  "do_it_yourself_store": "Retail & Shopping",
  "sporting_goods": "Retail & Shopping",
  "electrical_supply_store": "Retail & Shopping",
  "marketing_consultant": "Retail & Shopping",
  "livestock_feed_and_supply_store": "Retail & Shopping",
  "kitchen_supply_store": "Retail & Shopping",
  "battery_store": "Retail & Shopping",
  "drone_store": "Retail & Shopping",
  "souvenir_shop": "Retail & Shopping",
  "shopping_center": "Retail & Shopping",
  "t_shirt_store": "Retail & Shopping",
  "video_game_store": "Retail & Shopping",
  "custom_cakes_shop": "Retail & Shopping",
  "mens_clothing_store": "Retail & Shopping",
  "auto_body_shop": "Retail & Shopping",
  "horse_equipment_shop": "Retail & Shopping",
  "fabric_store": "Retail & Shopping",
  "avionics_shop": "Retail & Shopping",
  "electronics": "Retail & Shopping",
  "organic_grocery_store": "Retail & Shopping",
  "antique_store": "Retail & Shopping",
  "educational_supply_store": "Retail & Shopping",
  "motorsports_store": "Retail & Shopping",
  "custom_clothing": "Retail & Shopping",
  "superstore": "Retail & Shopping",
  "pop_up_shop": "Retail & Shopping",
  "wallpaper_store": "Retail & Shopping",
  "furniture_store": "Retail & Shopping",
  "military_surplus_store": "Retail & Shopping",
  "indian_sweets_shop": "Retail & Shopping",
  "cards_and_stationery_store": "Retail & Shopping",
  "archery_shop": "Retail & Shopping",
  "bird_shop": "Retail & Shopping",
  "lingerie_store": "Retail & Shopping",
  "used_bookstore": "Retail & Shopping",
  "home_goods_store": "Retail & Shopping",
  "dairy_stores": "Retail & Shopping",
  "clothing_store": "Retail & Shopping",
  "iron_and_steel_store": "Retail & Shopping",
  "ski_and_snowboard_shop": "Retail & Shopping",
  "clothing_rental": "Retail & Shopping",
  "rental_kiosks": "Retail & Shopping",
  "shopping": "Retail & Shopping",
  "department_store": "Retail & Shopping",
  "hat_shop": "Retail & Shopping",
  "adult_store": "Retail & Shopping",
  "costume_store": "Retail & Shopping",
  "e_cigarette_store": "Retail & Shopping",
  "bedding_and_bath_stores": "Retail & Shopping",
  "bicycle_shop": "Retail & Shopping",
  "safe_store": "Retail & Shopping",
  "drugstore": "Retail & Shopping",
  "handbag_stores": "Retail & Shopping",
  "wig_store": "Retail & Shopping",
  "tile_store": "Retail & Shopping",
  "baseball_field": "Sports & Recreation",
  "surfing": "Sports & Recreation",
  "volleyball_club": "Sports & Recreation",
  "go_kart_club": "Sports & Recreation",
  "go_kart_track": "Sports & Recreation",
  "rugby_pitch": "Sports & Recreation",
  "trail": "Sports & Recreation",
  "free_diving_center": "Sports & Recreation",
  "baseball_stadium": "Sports & Recreation",
  "disc_golf_course": "Sports & Recreation",
  "paintball": "Sports & Recreation",
  "professional_sports_league": "Sports & Recreation",
  "golf_instructor": "Sports & Recreation",
  "school_sports_team": "Sports & Recreation",
  "sky_diving": "Sports & Recreation",
  "paddleboarding_center": "Sports & Recreation",
  "sports_and_recreation_venue": "Sports & Recreation",
  "mountain_bike_trails": "Sports & Recreation",
  "canoe_and_kayak_hire_service": "Sports & Recreation",
  "horse_racing_track": "Sports & Recreation",
  "archery_range": "Sports & Recreation",
  "sailing_club": "Sports & Recreation",
  "fishing_charter": "Sports & Recreation",
  "hockey_arena": "Sports & Recreation",
  "professional_sports_team": "Sports & Recreation",
  "scuba_diving_center": "Sports & Recreation",
  "volleyball_court": "Sports & Recreation",
  "tennis_stadium": "Sports & Recreation",
  "school_sports_league": "Sports & Recreation",
  "table_tennis_club": "Sports & Recreation",
  "cricket_ground": "Sports & Recreation",
  "amateur_sports_league": "Sports & Recreation",
  "kiteboarding": "Sports & Recreation",
  "surfboard_rental": "Sports & Recreation",
  "kiteboarding_instruction": "Sports & Recreation",
  "tennis_court": "Sports & Recreation",
  "batting_cage": "Sports & Recreation",
  "climbing_class": "Sports & Recreation",
  "stadium_arena": "Sports & Recreation",
  "bocce_ball_court": "Sports & Recreation",
  "football_club": "Sports & Recreation",
  "golf_club": "Sports & Recreation",
  "paddleboard_rental": "Sports & Recreation",
  "bowling_alley": "Sports & Recreation",
  "sports_school": "Sports & Recreation",
  "diving_center": "Sports & Recreation",
  "racquetball_court": "Sports & Recreation",
  "tubing_provider": "Sports & Recreation",
  "court_reporter": "Sports & Recreation",
  "rafting_kayaking_area": "Sports & Recreation",
  "hiking_trail": "Sports & Recreation",
  "parasailing_ride_service": "Sports & Recreation",
  "swimming_pool": "Sports & Recreation",
  "laser_tag": "Sports & Recreation",
  "trailer_rentals": "Sports & Recreation",
  "ski_area": "Sports & Recreation",
  "aerial_tours": "Sports & Recreation",
  "esports_team": "Sports & Recreation",
  "rock_climbing_instructor": "Sports & Recreation",
  "rugby_stadium": "Sports & Recreation",
  "squash_court": "Sports & Recreation",
  "handball_court": "Sports & Recreation",
  "soccer_club": "Sports & Recreation",
  "skate_park": "Sports & Recreation",
  "horse_boarding": "Sports & Recreation",
  "courthouse": "Sports & Recreation",
  "rock_climbing_spot": "Sports & Recreation",
  "mountain_bike_parks": "Sports & Recreation",
  "golf_cart_rental": "Sports & Recreation",
  "ski_resort": "Sports & Recreation",
  "soccer_stadium": "Sports & Recreation",
  "sledding_rental": "Sports & Recreation",
  "amateur_sports_team": "Sports & Recreation",
  "equestrian_facility": "Sports & Recreation",
  "sports_wear": "Sports & Recreation",
  "snorkeling": "Sports & Recreation",
  "bounce_house_rental": "Sports & Recreation",
  "adventure_sports_center": "Sports & Recreation",
  "golf_course": "Sports & Recreation",
  "trampoline_park": "Sports & Recreation",
  "wildlife_hunting_range": "Sports & Recreation",
  "basketball_stadium": "Sports & Recreation",
  "roller_skating_rink": "Sports & Recreation",
  "scuba_diving_instruction": "Sports & Recreation",
  "axe_throwing": "Sports & Recreation",
  "rowing_club": "Sports & Recreation",
  "badminton_court": "Sports & Recreation",
  "basketball_court": "Sports & Recreation",
  "miniature_golf_course": "Sports & Recreation",
  "track_stadium": "Sports & Recreation",
  "bubble_soccer_field": "Sports & Recreation",
  "sailing_area": "Sports & Recreation",
  "indoor_golf_center": "Sports & Recreation",
  "airsoft_fields": "Sports & Recreation",
  "beach_volleyball_court": "Sports & Recreation",
  "climbing_service": "Sports & Recreation",
  "horse_riding": "Sports & Recreation",
  "ice_skating_rink": "Sports & Recreation",
  "skating_rink": "Sports & Recreation",
  "esports_league": "Sports & Recreation",
  "hockey_field": "Sports & Recreation",
  "hunting_and_fishing_supplies": "Sports & Recreation",
  "football_stadium": "Sports & Recreation",
  "fishing_club": "Sports & Recreation",
  "ski_and_snowboard_school": "Sports & Recreation",
  "race_track": "Sports & Recreation",
  "soccer_field": "Sports & Recreation",
  "surfing_school": "Sports & Recreation",
  "shooting_range": "Sports & Recreation",
  "sports_club_and_league": "Sports & Recreation",
  "paddle_tennis_club": "Sports & Recreation",
  "data_recovery": "Technology & IT",
  "credit_and_debt_counseling": "Technology & IT",
  "web_hosting_service": "Technology & IT",
  "home_network_installation": "Technology & IT",
  "biotechnology_company": "Technology & IT",
  "software_development": "Technology & IT",
  "attraction_farm": "Tourism & Attractions",
  "scooter_tours": "Tourism & Attractions",
  "whale_watching_tours": "Tourism & Attractions",
  "beer_tours": "Tourism & Attractions",
  "lighthouse": "Tourism & Attractions",
  "fountain": "Tourism & Attractions",
  "historical_tours": "Tourism & Attractions",
  "wine_tours": "Tourism & Attractions",
  "palace": "Tourism & Attractions",
  "memorial_park": "Tourism & Attractions",
  "atv_rentals_and_tours": "Tourism & Attractions",
  "attractions_and_activities": "Tourism & Attractions",
  "sculpture_statue": "Tourism & Attractions",
  "monument": "Tourism & Attractions",
  "lookout": "Tourism & Attractions",
  "walking_tours": "Tourism & Attractions",
  "fort": "Tourism & Attractions",
  "tours": "Tourism & Attractions",
  "visitor_center": "Tourism & Attractions",
  "landmark_and_historical_building": "Tourism & Attractions",
  "bus_tours": "Tourism & Attractions",
  "boat_tours": "Tourism & Attractions",
  "castle": "Tourism & Attractions",
  "bike_tours": "Tourism & Attractions",
  "business_storage_and_transportation": "Transportation",
  "transport_interchange": "Transportation",
  "seaplane_bases": "Transportation",
  "railroad_freight": "Transportation",
  "sport_equipment_rentals": "Transportation",
  "airport_shuttles": "Transportation",
  "importers": "Transportation",
  "heliports": "Transportation",
  "ferry_service": "Transportation",
  "ride_sharing": "Transportation",
  "bus_station": "Transportation",
  "balloon_ports": "Transportation",
  "train_station": "Transportation",
  "railway_service": "Transportation",
  "parking": "Transportation",
  "disability_services_and_support_organization": "Transportation",
  "major_airports": "Transportation",
  "gliderports": "Transportation",
  "railway_ticket_agent": "Transportation",
  "limo_services": "Transportation",
  "transportation": "Transportation",
  "airline": "Transportation",
  "ferry_boat_company": "Transportation",
  "taxi_service": "Transportation",
  "airlines": "Transportation",
  "importer_and_exporter": "Transportation",
  "light_rail_and_subway_stations": "Transportation",
  "taxidermist": "Transportation",
  "pet_transportation": "Transportation",
  "metro_station": "Transportation",
  "airport": "Transportation",
  "it_support_and_service": "Transportation",
  "bike_parking": "Transportation",
  "exporters": "Transportation",
  "airport_terminal": "Transportation",
  "pet_waste_removal": "Utilities & Infrastructure",
  "dam": "Utilities & Infrastructure",
  "electrical_wholesaler": "Utilities & Infrastructure",
  "garbage_collection_service": "Utilities & Infrastructure",
  "telecommunications": "Utilities & Infrastructure",
  "utility_service": "Utilities & Infrastructure",
  "energy_equipment_and_solution": "Utilities & Infrastructure",
  "power_plants_and_power_plant_service": "Utilities & Infrastructure",
  "water_supplier": "Utilities & Infrastructure",
  "energy_company": "Utilities & Infrastructure",
  "toll_stations": "Utilities & Infrastructure",
  "telecommunications_company": "Utilities & Infrastructure",
  "pipeline_transportation": "Utilities & Infrastructure",
  "wind_energy": "Utilities & Infrastructure",
  "internet_service_provider": "Utilities & Infrastructure",
  "home_energy_auditor": "Utilities & Infrastructure",
  "bridge": "Utilities & Infrastructure",
  "electricity_supplier": "Utilities & Infrastructure",
  "electric_utility_provider": "Utilities & Infrastructure",
  "recycling_center": "Utilities & Infrastructure",
  "b2b_energy_and_mining": "Utilities & Infrastructure",
  "telephone_services": "Utilities & Infrastructure",
  "hazardous_waste_disposal": "Utilities & Infrastructure"
};
  
  // Return the mapped primary category, or null if not found
  if (CATEGORY_LABEL === null || CATEGORY_LABEL === undefined) {
    return null;
  }
  
  // Convert to lowercase for case-insensitive matching
  var label = CATEGORY_LABEL.toLowerCase();
  
  return categoryMapping[label] || null;
$$;

-- Example usage:
-- SELECT MAP_CATEGORY_LABEL_TO_PRIMARY('thai_restaurant');
-- Returns: 'Food & Dining'
--
-- SELECT MAP_CATEGORY_LABEL_TO_PRIMARY('hotel');
-- Returns: 'Accommodation & Lodging'
--
-- SELECT category_label, MAP_CATEGORY_LABEL_TO_PRIMARY(category_label) as category_primary
-- FROM your_table;
